namespace CheatTools
{
    internal enum DesireEng
    {
        ChangeClothes = 0,
        GoToToilet = 1,
        TakeShower = 2,
        HaveMeal = 3,
        HMasturbate = 4,
        HWithPlayer = 5,
        DoClubActivities = 6,
        TalkWithGirls = 7,
        TalkWithPlayer = 8,
        Read = 9,
        FiddleWithSmartphone = 10,
        GameOnSmartphone = 11,
        TakeSelfie = 12,
        ListenToMusic = 13,
        DancePractice = 14,
        ImproveMyAppearance = 15,
        Drink = 16,
        ChangeMyMind = 17,
        Exercise = 18,
        CharaSpecificBehavior = 19,
        GetAway = 20,
        Study = 21,
        Sleep = 22,
        FollowMe = 23,
        Request = 24,
        Shy = 25,
        Lesbian = 26,
        LesbianPartner = 27,
        AskPlayerToTalk = 28,
        AskPlayerForH = 29,
        FidgetingWaiting = 30,

        // New in KKS
        TakeBath = 31,
        TakeBreak = 32,
        Leisure = 33,
        GoShopping = 34,
        Experience = 35,
        Sightseeing = 36,
        OilSalon = 37,
        WatermelonSplit = 38,
        WatermelonSplitPartner = 39,
        SittingTalking = 40,
        SittingTalkingPartner = 41,
        SplashingWater = 42,
        SplashingWaterPartner = 43,
        Vacation = 44,
        Outdoors = 45,
        Curiosity = 46
    }
}
